Repository ZenBit-Tech/code-lions_fe, pull requests merged in 2024-07, with the labels that each got.

#29 feat: public profile connection, buyer page
  jest.config.ts
  package-lock.json
  package.json
  src/__tests__/reduxProvider.tsx
  src/__tests__/reduxQueries.test.ts
  src/assets/icons/vendor/raitingOrders.svg
  src/common/constants.ts
  src/common/useUserProfileData.ts
  src/components/shared/ArrowButtonTo/index.tsx
  src/components/shared/CommentCard/index.tsx
  src/components/shared/CommentCard/styles.ts
  src/components/shared/CommentList/index.tsx
  src/config/config.ts
  src/locales/en/index.json
  src/pages/BuyerProfilePage/ProfileInfo/index.tsx
  src/pages/BuyerProfilePage/ProfileInfo/styles.ts
  src/pages/BuyerProfilePage/index.tsx
  src/pages/BuyerProfilePage/styles.ts
  src/pages/VendorProfilePage/ProfileInfo/index.tsx
  src/pages/VendorProfilePage/index.tsx
  src/pages/VendorProfilePage/styles.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/routes/routes.tsx
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#34 Feat/best vendors
  package-lock.json
  src/assets/photos/check-filters.png
  src/common/constants.ts
  src/components/ProductFilters/index.tsx
  src/components/ProductFilters/styles.ts
  src/locales/en/index.json
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
  src/pages/BestVendorsPage/index.tsx
  src/routes/routes.tsx
Labels: enhancement

#33 feat: creating new home page
  package-lock.json
  package.json
  src/assets/icons/arrow-left-slider.svg
  src/assets/icons/arrow-right-slider.svg
  src/assets/photos/categories/accessories.jpg
  src/assets/photos/categories/bag.jpg
  src/assets/photos/categories/clothing.jpg
  src/assets/photos/categories/designers.jpg
  src/assets/photos/categories/shoes.jpg
  src/assets/photos/image2.jpg
  src/assets/photos/womanWithBag.png
  src/common/constants.ts
  src/components/shared/CommentCard/index.tsx
  src/locales/en/index.json
  src/main.tsx
  src/pages/BuyerProfilePage/ProfileInfo/styles.ts
  src/pages/BuyerProfilePage/index.tsx
  src/pages/BuyerPublicProfilePage/ProfileInfo/index.tsx
  src/pages/BuyerPublicProfilePage/ProfileInfo/styles.ts
  src/pages/BuyerPublicProfilePage/index.tsx
  src/pages/BuyerPublicProfilePage/styles.ts
  src/pages/HomePage/Announcement/index.tsx
  src/pages/HomePage/Announcement/styles.ts
  src/pages/HomePage/CategoriesSlider/index.tsx
  src/pages/HomePage/CategoriesSlider/styles.ts
  src/pages/HomePage/Products/index.tsx
  src/pages/HomePage/Products/styles.ts
  src/pages/HomePage/index.tsx
  src/pages/VendorProfilePage/ProfileInfo/index.tsx
  src/pages/VendorProfilePage/ProfileInfo/styles.ts
  src/pages/VendorProfilePage/index.tsx
  src/pages/VendorProfilePage/styles.ts
  src/pages/vendor/VendorPublicProfilePage/ProfileInfo/index.tsx
  src/pages/vendor/VendorPublicProfilePage/ProfileInfo/styles.ts
  src/pages/vendor/VendorPublicProfilePage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/styles.ts
  src/routes/routes.tsx
Labels: enhancement

#35 Fix/fixing bugs with public profiles
  src/assets/icons/vendor/raitingOrders.svg
  src/common/constants.ts
  src/common/useUserProfileData.ts
  src/components/shared/ArrowButtonTo/index.tsx
  src/components/shared/CommentList/index.tsx
  src/redux/user/types.ts
Labels: enhancement

#37 Refactor/product filters
  src/components/Header/index.tsx
  src/components/ProductFilters/index.tsx
  src/locales/en/index.json
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
Labels: enhancement

#41 Feat/home page connect
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/HomePage/Products/index.tsx
  src/redux/product/productService.test.tsx
  src/redux/product/productService.ts
  src/redux/user/userSlice.ts
  src/test/mocks/latestProducts.ts
  src/test/mocks/productsBySizes.ts
Labels: enhancement

#38 Feat/connect best vendors
  package-lock.json
  src/common/constants.ts
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
  src/redux/bestVendors/bestVendorsService.test.tsx
  src/redux/bestVendors/bestVendorsService.ts
  src/redux/bestVendors/bestVendorsSlice.ts
  src/redux/bestVendors/types.ts
  src/redux/product/productService.test.tsx
  src/redux/product/productService.ts
  src/redux/store.ts
  src/test/handlers.ts
  src/test/mocks/allvendors.ts
  src/test/setup.ts
Labels: enhancement, feature

#42 Feat/checkout
  src/assets/icons/trash-bin.svg
  src/common/constants.ts
  src/components/Header/index.tsx
  src/locales/en/index.json
  src/pages/CartPage/CartTable/index.tsx
  src/pages/CartPage/CartTable/styles.ts
  src/pages/CartPage/index.tsx
  src/pages/CartPage/styles.ts
  src/pages/CheckoutPage/CartSummary/index.tsx
  src/pages/CheckoutPage/CartSummary/styles.ts
  src/pages/CheckoutPage/CartSummary/useCartSummaryHook.test.ts
  src/pages/CheckoutPage/CartSummary/useCartSummaryHook.ts
  src/pages/CheckoutPage/index.tsx
  src/pages/ProfileLayout/index.tsx
  src/pages/ProfilePage/PhotoUploadForm/index.tsx
  src/redux/cart/cartSlice.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: enhancement, markup

#45 Feat/product list
  src/assets/photos/no-image.jpg
  src/common/constants.ts
  src/common/utils/formatToTwoDecimalPlaces.ts
  src/common/utils/tests/formatToTwoDecimalPlaces.test.ts
  src/components/ProductTableCard/index.tsx
  src/components/ProductTableCard/styles.ts
  src/components/shared/StyledBackdrop/index.tsx
  src/locales/en/index.json
  src/pages/admin/AdminUserProfilePage/UserDetailsSection.tsx
  src/pages/admin/UsersPage/UsersTable/index.tsx
  src/pages/vendor/VendorProductsPage/ActionButtons/index.tsx
  src/pages/vendor/VendorProductsPage/ModalPopup/index.tsx
  src/pages/vendor/VendorProductsPage/ModalPopup/styles.ts
  src/pages/vendor/VendorProductsPage/ProductsTable/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/productsMock.ts
  src/pages/vendor/VendorProductsPage/ProductsTable/styles.ts
  src/pages/vendor/VendorProductsPage/index.tsx
  src/pages/vendor/VendorProductsPage/styles.ts
  src/redux/product/types.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: markup

#43 feat: created vendor-add-product-page / categories form
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorAddProductPage/index.tsx
  src/redux/addProduct/addProductSlice.ts
  src/redux/addProduct/types.ts
  src/redux/store.ts
  src/routes/routes.tsx
Labels: enhancement, feature, markup

#39 Feat/products search & fixes from demo
  package-lock.json
  package.json
  src/assets/icons/tick-grey.svg
  src/assets/icons/tick-white.svg
  src/common/constants.ts
  src/common/selectSizeOptions.ts
  src/common/utils/createNavigationLink.ts
  src/common/utils/tests/createNavigationLink.test.ts
  src/components/FooterMenu/index.tsx
  src/components/FooterMenu/menuData.ts
  src/components/Layout/index.tsx
  src/components/ProductCard/index.test.tsx
  src/components/ProductFilters/PriceFilter/index.tsx
  src/components/ProductFilters/PriceFilter/styles.css
  src/components/ProductFilters/PriceFilter/styles.ts
  src/components/ProductFilters/index.tsx
  src/components/ProductFilters/styles.ts
  src/components/ScrollToTop/index.tsx
  src/components/SelectedFilters/index.tsx
  src/components/shared/OrderSelector/index.tsx
  src/components/shared/StyledButton/index.tsx
  src/locales/en/index.json
  src/main.test.tsx
  src/pages/AboutUsPage/index.tsx
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
  src/pages/BestVendorsPage/index.tsx
  src/pages/CompanyPage/index.tsx
  src/pages/ContactPage/index.tsx
  src/pages/FaqPage/index.tsx
  src/pages/HelpPage/index.tsx
  src/pages/HomePage/CategoriesSlider/index.tsx
  src/pages/HomePage/Products/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/OnboardingPage/InfoForm/index.tsx
  src/pages/OnboardingPage/SizeForm/index.tsx
  src/pages/PrivacyPolicyPage/index.tsx
  src/pages/ProductFeedPage/index.test.tsx
  src/pages/ProductFeedPage/index.tsx
  src/pages/ProductFeedPage/useProductFeed.ts
  src/pages/ProductPage/DescriptionSection.tsx
  src/pages/ProfilePage/PhotoUploadForm/index.tsx
  src/pages/RentPage/index.tsx
  src/pages/ShippingPage/index.tsx
  src/pages/SizesGuidePage/index.tsx
  src/pages/SizesGuidePage/tableData.ts
  src/pages/WishlistPage/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/productsMock.ts
  src/redux/product/productService.test.tsx
  src/redux/product/productService.ts
  src/redux/product/types.ts
  src/routes/routes.tsx
  src/test/handlers.ts
  src/test/mocks/allProducts.ts
  src/test/mocks/wishlist.ts
  src/test/setup.ts
Labels: enhancement, feature

#47 fix: changed mocks
  src/components/ProductCard/index.test.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/productsMock.ts
  src/redux/product/types.ts
  src/test/mocks/allProducts.ts
  src/test/mocks/allvendors.ts
  src/test/mocks/latestProducts.ts
  src/test/mocks/productsBySizes.ts
Labels: hotfix

#52 Feat/vendor product
  src/common/constants.ts
  src/components/SidebarAdmin/index.tsx
  src/locales/en/index.json
  src/pages/admin/AdminChatsPage/index.tsx
  src/pages/admin/ProductRequestPage/index.tsx
  src/pages/admin/ProductsTable/index.tsx
  src/pages/vendor/VendorLayout/VendorHeader/index.tsx
  src/pages/vendor/VendorProductsPage/ActionButtons/index.tsx
  src/pages/vendor/VendorProductsPage/ModalPopup/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/index.tsx
  src/pages/vendor/VendorProductsPage/ProductsTable/productsMock.ts
  src/pages/vendor/VendorProductsPage/index.tsx
  src/pages/vendor/VendorProfileLayout/index.tsx
  src/pages/vendor/VendorProfilePage/AvatarUploader/index.tsx
  src/redux/store.ts
  src/redux/user/types.ts
  src/redux/vendorProduct/types.ts
  src/redux/vendorProduct/vendorProductService.ts
  src/routes/routes.tsx
Labels: enhancement

#54 Feat/add product 1-4 connect
  src/assets/icons/addProduct/oval.svg
  src/common/constants.ts
  src/components/shared/ImageCard/index.tsx
  src/components/shared/ImageCard/useImageCard.ts
  src/components/shared/ImageForm/index.tsx
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorAddProductPage/FinishForm/styles.ts
  src/pages/vendor/VendorAddProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorAddProductPage/index.tsx
  src/pages/vendor/VendorLayout/VendorSideBar/index.tsx
  src/redux/addProduct/addProductService.ts
  src/redux/addProduct/addProductSlice.ts
  src/redux/addProduct/types.ts
  src/redux/store.ts
Labels: enhancement

#55 Feat/rental rules
  src/common/constants.ts
  src/components/FooterMenu/menuData.ts
  src/components/Header/index.tsx
  src/locales/en/index.json
  src/pages/ProductPage/DescriptionSection.tsx
  src/pages/ProductPage/ProductSection.tsx
  src/pages/ProductPage/RadioLabel.tsx
  src/pages/ProductPage/RentalRulesPopup.tsx
  src/pages/ProductPage/hooks/useProductSection.ts
  src/pages/ProductPage/hooks/useRentalRulesPopup.ts
  src/pages/ProductPage/styles.ts
  src/pages/ProductPage/utils/processStringArray.spec.ts
  src/pages/ProductPage/utils/processStringArray.ts
  src/pages/RentalRulesPage/index.tsx
  src/pages/RentalRulesPage/rulesData.ts
  src/pages/RentalRulesPage/styles.ts
  src/redux/product/types.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/routes.tsx
Labels: enhancement, feature, markup

#56 Feat/connect add product step3
  src/common/constants.ts
  src/components/ReusableDescriptionBox/index.tsx
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/constants.ts
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/hooks/useProductDispatch.ts
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/redux/addProduct/addProductService.ts
  src/redux/addProduct/addProductSlice.ts
  src/redux/addProduct/types.ts
Labels: enhancement, feature

#58 refactor: refactored checkout page with useGroupedByVendor Hook to gr…
  src/locales/en/index.json
  src/pages/CheckoutPage/CartSummary/index.tsx
  src/pages/CheckoutPage/CartSummary/useCartSummaryHook.test.ts
  src/pages/CheckoutPage/CartSummary/useCartSummaryHook.ts
  src/pages/CheckoutPage/CheckoutTable/index.tsx
  src/pages/CheckoutPage/index.tsx
  src/pages/CheckoutPage/useGroupedByVendorHook.test.ts
  src/pages/CheckoutPage/useGroupedByVendorHook.ts
  src/redux/cart/types.ts
  src/test/mocks/cart.ts
Labels: enhancement

#59 Feat/rental rules connect
  src/components/ProductCard/ProductCardRulesPopup.tsx
  src/components/ProductCard/RulesErrorPopup.tsx
  src/components/ProductCard/SelectDurationPopup.tsx
  src/components/ProductCard/hooks/useProductCard.ts
  src/components/ProductCard/hooks/useProductCardRulesPopup.ts
  src/components/ProductCard/index.tsx
  src/components/ProductCard/styles.ts
  src/components/ProductCard/useProductCard.ts
  src/components/shared/toasts/components/ToastProvider/index.tsx
  src/locales/en/index.json
  src/pages/ProductPage/DescriptionSection.tsx
  src/pages/ProductPage/ProductSection.tsx
  src/pages/ProductPage/RadioLabel.tsx
  src/pages/ProductPage/hooks/useProductSection.ts
  src/pages/WishlistPage/index.tsx
  src/redux/product/types.ts
  src/redux/user/types.ts
  src/redux/user/userSlice.ts
Labels: enhancement, feature, markup

#62 Fear/vendor order page markup
  src/assets/icons/vendor/chat-white.svg
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/vendor/VendorOrderPage/BuyerInfoSection.tsx
  src/pages/vendor/VendorOrderPage/OrderDetailsSection.tsx
  src/pages/vendor/VendorOrderPage/OrderInfoSection.tsx
  src/pages/vendor/VendorOrderPage/OrderProductsTable.tsx
  src/pages/vendor/VendorOrderPage/OrderSummarySection.tsx
  src/pages/vendor/VendorOrderPage/index.tsx
  src/pages/vendor/VendorOrderPage/mockData.ts
  src/pages/vendor/VendorOrderPage/styles.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: markup

#64 Profile orders markup
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/ProfileOrders/OrderCard/index.tsx
  src/pages/ProfileOrders/OrderCard/styles.ts
  src/pages/ProfileOrders/index.tsx
  src/pages/ProfileOrders/styles.ts
  src/routes/routes.tsx
Labels: feature, markup
