Repository ZenBit-Tech/code-lions_fe, pull requests merged in 2024-08, with the labels that each got.

#66 feat/added vendor closet tab to vendor public profile
  src/locales/en/index.json
  src/pages/WishlistPage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/hooks/useVendorPublicProfile.ts
  src/pages/vendor/VendorPublicProfilePage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/styles.ts
  src/redux/vendorProduct/vendorProductService.ts
Labels: enhancement, markup

#71 Feat/vendor dashboard connect
  src/common/constants.ts
  src/pages/vendor/VendorDashboard/OrdersTable/index.tsx
  src/pages/vendor/VendorDashboard/VendorPieChart/index.tsx
  src/pages/vendor/VendorDashboard/VendorPieChartLegend/index.tsx
  src/pages/vendor/VendorDashboard/index.tsx
  src/pages/vendor/VendorDashboard/mockOrderData.ts
  src/pages/vendor/VendorDashboard/types.ts
  src/pages/vendor/VendorDashboard/useSalesDataHook.ts
  src/pages/vendor/VendorOrdersPage/OrdersTable/index.tsx
  src/pages/vendor/VendorOrdersPage/index.tsx
  src/pages/vendor/VendorProductsPage/index.tsx
  src/redux/order/orderService.ts
  src/redux/order/types.ts
  src/redux/store.ts
Labels: enhancement

#74 Refactor/add product
  package-lock.json
  src/assets/icons/addProduct/success-icon.svg
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorAddProductPage/VerificationModal/index.tsx
  src/pages/vendor/VendorAddProductPage/VerificationModal/styles.ts
Labels: enhancement

#60 Feat/stripe button
  src/common/constants.ts
  src/components/Header/index.tsx
  src/components/shared/ImageForm/index.tsx
  src/locales/en/index.json
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
  src/pages/BestVendorsPage/index.tsx
  src/pages/CheckoutPage/CartSummary/index.tsx
  src/pages/CheckoutPage/CartSummary/useCartSummaryHook.ts
  src/pages/CheckoutPage/index.tsx
  src/pages/OnboardingPage/StripeForm/index.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/ProductFeedPage/useProductFeed.ts
  src/pages/vendor/VendorDashboard/VendorPieChart/index.tsx
  src/pages/vendor/VendorDashboard/types.ts
  src/redux/bestVendors/bestVendorsService.test.tsx
  src/redux/bestVendors/bestVendorsService.ts
  src/redux/cart/cartService.ts
  src/redux/cart/types.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/routes/FinishedOnboardingGuard.tsx
  src/routes/OnboardingGuard.tsx
Labels: enhancement, feature

#75 Feat/buyers review
  src/components/shared/CommentCard/index.tsx
  src/components/shared/CommentCard/styles.ts
  src/pages/Chats/components/ChatAvatar.tsx
  src/pages/Chats/components/ChatLink.tsx
Labels: enhancement

#67 Feat/vendor sidebar
  src/pages/vendor/VendorLayout/VendorSideBar/index.tsx
  src/pages/vendor/VendorLayout/VendorSideBar/styles.ts
Labels: enhancement

#79 fix/removed userId from get single order request
  src/pages/ProfileOrder/index.tsx
  src/pages/vendor/VendorOrderPage/index.tsx
  src/pages/vendor/VendorOrdersPage/OrdersTable/index.tsx
Labels: hotfix

#78 Feat/connect follow vendor
  src/common/constants.ts
  src/components/shared/ImageForm/index.tsx
  src/locales/en/index.json
  src/pages/BestVendorsPage/BestVendorsList/index.tsx
  src/redux/bestVendors/bestVendorsService.ts
  src/redux/bestVendors/bestVendorsSlice.ts
  src/redux/bestVendors/types.ts
  src/redux/store.ts
Labels: enhancement

#81 Feat/update order markup
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/ProfileOrder/OrderInfoSection.tsx
  src/pages/ProfileOrder/index.tsx
  src/pages/vendor/VendorOrderPage/OrderActionComponents.tsx
  src/pages/vendor/VendorOrderPage/OrderActions.tsx
  src/pages/vendor/VendorOrderPage/OrderInfoSection.tsx
  src/pages/vendor/VendorOrderPage/RejectOrderModal.tsx
  src/pages/vendor/VendorOrderPage/index.tsx
  src/pages/vendor/VendorOrderPage/styles.ts
  src/pages/vendor/VendorOrdersPage/OrdersTable/styles.ts
Labels: feature, markup

#85 Feat/settings
  src/assets/icons/eye.svg
  src/locales/en/index.json
  src/pages/ProfilePage/AddressForm/index.tsx
  src/pages/ProfilePage/PersonalInformationForm/index.tsx
  src/pages/ProfilePage/PersonalInformationForm/schema.ts
  src/pages/ProfilePage/PersonalInformationForm/styles.ts
  src/pages/ProfilePage/ProfileComingSoon/index.tsx
  src/pages/ProfilePage/SizesFrom/index.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/ProfilePage/styles.ts
  src/pages/SettingsPage/ChangeEmailForm/index.tsx
  src/pages/SettingsPage/ChangeEmailForm/schema.ts
  src/pages/SettingsPage/ChangePasswordForm/index.tsx
  src/pages/SettingsPage/ChangePasswordForm/shema.ts
  src/pages/SettingsPage/index.tsx
  src/pages/SettingsPage/schema.ts
  src/pages/SettingsPage/styles.ts
  src/routes/routes.tsx
Labels: markup

#84 Refactor and bugfixing/add edit product
  src/components/shared/RejectProductFlowModal/index.tsx
  src/components/shared/RejectProductFlowModal/styles.ts
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/hooks/useGetProductBrands.ts
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/hooks/useProductDispatch.ts
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/productDescriptionConstants.ts
  src/pages/vendor/VendorEditProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorEditProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorEditProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorEditProductPage/ProductDescriptionForm/hooks/useProductDispatch.ts
  src/pages/vendor/VendorEditProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorEditProductPage/index.tsx
  src/redux/addProduct/addProductSlice.ts
  src/redux/bestVendors/bestVendorsSlice.ts
  src/redux/vendorProduct/vendorProductService.ts
Labels: bug, enhancement

#89 Fix/routing
  src/common/constants.ts
  src/components/Header/index.tsx
  src/locales/en/index.json
  src/pages/OnboardingPage/index.tsx
  src/pages/ProfileOrders/index.tsx
  src/pages/RentalRulesPage/index.tsx
  src/pages/SignInPage/SignInForm/index.tsx
  src/pages/TermsOfUsePage/styles.ts
  src/pages/VerifyEmailPage/hooks/useVerification.ts
  src/pages/VerifyEmailPage/index.tsx
  src/pages/admin/SignInAdminPage/SignInAdminForm/index.tsx
  src/routes/ForbiddenRoute.tsx
  src/routes/OnboardingGuard.tsx
  src/routes/VendorGuard.tsx
  src/routes/VendorPrivateRoute.tsx
  src/routes/routes.tsx
Labels: bug, enhancement

#90 fix: redirect to verify only unverified users
  src/locales/en/index.json
  src/routes/OnboardingGuard.tsx
Labels: hotfix

#87 Feat/settings
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/SettingsPage/ChangeEmailForm/index.tsx
  src/pages/SettingsPage/ChangePasswordForm/index.tsx
  src/pages/SettingsPage/DeleteAccountPopup/index.tsx
  src/pages/SettingsPage/index.tsx
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
Labels: enhancement

#83 Feat/stripe fees
  src/assets/icons/admin/stripe.svg
  src/common/constants.ts
  src/components/SidebarAdmin/index.tsx
  src/locales/en/index.json
  src/pages/admin/Stripe/index.tsx
  src/pages/admin/Stripe/styles.ts
  src/redux/store.ts
  src/redux/stripe/stripeService.ts
  src/routes/routes.tsx
Labels: feature

#86 refactor: added follow-vendor button server connection at ProfileInfo…
  src/pages/vendor/VendorPublicProfilePage/ProfileInfo/index.tsx
  src/pages/vendor/VendorPublicProfilePage/index.tsx
Labels: bug, enhancement

#88 refactor: added logic to open reject product modal when user is leavi…
  src/components/shared/RejectProductFlowModal/hooks/useRejectProductFlowModal.ts
  src/components/shared/RejectProductFlowModal/index.tsx
  src/pages/vendor/VendorAddProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorAddProductPage/VerificationModal/index.tsx
  src/pages/vendor/VendorEditProductPage/CategoriesForm/index.tsx
  src/pages/vendor/VendorEditProductPage/FinishForm/index.tsx
  src/pages/vendor/VendorEditProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorEditProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorLayout/VendorSideBar/index.tsx
  src/pages/vendor/VendorProductsPage/ActionButtons/index.tsx
  src/redux/addProduct/addProductSlice.ts
  src/redux/addProduct/types.ts
Labels: bug, enhancement

#92 Bugfix/add edit product step one
  src/components/shared/ImageCard/index.tsx
  src/components/shared/ImageForm/index.tsx
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/ImagesForm/index.tsx
  src/pages/vendor/VendorEditProductPage/ImagesForm/index.tsx
  src/redux/bestVendors/bestVendorsSlice.ts
  src/theme.tsx
Labels: bug, enhancement

#95 refactor: added missing product properties at DescriptionSection / ad…
  src/locales/en/index.json
  src/pages/vendor/VendorProductPage/DescriptionSection.tsx
  src/pages/vendor/VendorProductPage/index.tsx
  src/pages/vendor/VendorProductsPage/ModalPopup/index.tsx
Labels: bug, enhancement

#97 fix: added ModalPopupReject for admin at public product page
  src/pages/vendor/VendorProductPage/index.tsx
Labels: hotfix

#98 fix: added go back navigation for admin
  src/pages/vendor/VendorProductPage/index.tsx
Labels: hotfix

#96 Fix/frontend fixes
  src/locales/en/index.json
  src/pages/ProductPage/index.tsx
  src/pages/ProfileOrder/OrderSummarySection.tsx
  src/pages/ProfileOrder/index.tsx
  src/pages/WishlistPage/index.tsx
  src/pages/vendor/VendorOrderPage/OrderActionComponents.tsx
  src/pages/vendor/VendorOrderPage/OrderActions.tsx
  src/pages/vendor/VendorOrderPage/OrderSummarySection.tsx
  src/pages/vendor/VendorOrderPage/index.tsx
  src/pages/vendor/VendorProductPage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/hooks/useVendorPublicProfile.ts
  src/pages/vendor/VendorPublicProfilePage/index.tsx
  src/redux/order/types.ts
Labels: bug

#91 Feat/notifications
  src/common/constants.ts
  src/common/hooks/useNotificationSocket.ts
  src/components/Header/index.tsx
  src/locales/en/index.json
  src/pages/Notifications/index.tsx
  src/pages/Notifications/styles.ts
  src/pages/vendor/VendorLayout/VendorHeader/index.tsx
  src/pages/vendor/VendorLayout/VendorHeader/styles.ts
  src/redux/notification/notificationsService.ts
  src/redux/notification/notificationsSlice.ts
  src/redux/notification/types.ts
  src/redux/store.ts
  src/routes/routes.tsx
Labels: enhancement

#82 feat/add new query getAllPaginatedOrdersVendor to orderService, updat…
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/ProfileOrders/OrderCard/index.tsx
  src/pages/ProfileOrders/index.tsx
  src/pages/admin/AdminSectionTitle/index.tsx
  src/pages/admin/UsersPage/index.tsx
  src/pages/vendor/VendorDashboard/VendorPieChart/index.tsx
  src/pages/vendor/VendorDashboard/useSalesDataHook.ts
  src/pages/vendor/VendorOrderPage/OrderActions.tsx
  src/pages/vendor/VendorOrdersPage/OrderButtons/index.tsx
  src/pages/vendor/VendorOrdersPage/OrdersTable/index.tsx
  src/pages/vendor/VendorOrdersPage/OrdersTable/styles.ts
  src/pages/vendor/VendorOrdersPage/index.tsx
  src/redux/order/orderService.ts
  src/redux/order/types.ts
Labels: enhancement

#94 Profile orders
  src/common/constants.ts
  src/common/millisecondsToDays.ts
  src/locales/en/index.json
  src/pages/ProfileOrders/OrderCard/index.tsx
  src/pages/ProfileOrders/index.tsx
  src/pages/vendor/VendorOrderPage/OrderActionComponents.tsx
  src/pages/vendor/VendorOrderPage/OrderActions.tsx
  src/redux/order/orderService.ts
  src/redux/order/types.ts
Labels: enhancement

#99 fix: fixed grouping sizes logic at add/edit product pages
  src/components/shared/RejectProductFlowModal/index.tsx
  src/locales/en/index.json
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/hooks/useProductDispatch.ts
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/index.tsx
  src/pages/vendor/VendorAddProductPage/ProductDescriptionForm/productDescriptionConstants.ts
  src/pages/vendor/VendorEditProductPage/ProductDescriptionForm/hooks/useProductDispatch.ts
  src/pages/vendor/VendorEditProductPage/ProductDescriptionForm/index.tsx
Labels: hotfix

#102 Feat/vendor orders connect
  src/pages/vendor/VendorDashboard/OrdersTable/index.tsx
Labels: hotfix

#103 Fix/product layout
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/Chats/components/MessageBody.tsx
  src/pages/ProductPage/ImagesSection.tsx
  src/pages/ProductPage/ProductSection.tsx
  src/pages/ProductPage/hooks/useImageSection.ts
  src/pages/SignUpPage/SignUpForm/index.tsx
  src/pages/vendor/VendorProductPage/ImagesSection.tsx
  src/pages/vendor/VendorProfilePage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/index.tsx
  src/pages/vendor/VendorPublicProfilePage/styles.ts
  src/redux/api.ts
  src/redux/cart/cartService.ts
  src/redux/service.ts
  src/redux/user/userService.ts
Labels: bug, feature
