Repository ZenBit-Tech/code-lions_fe, pull requests merged in 2024-06, with the labels that each got.

#5 Feat/signup
  .eslintrc.cjs
  src/components/SignUpForm/index.tsx
  src/components/SignUpForm/styles.ts
  src/components/shared/Container/index.tsx
  src/components/shared/InputWrapper/index.tsx
  src/components/shared/LabelText/index.tsx
  src/components/shared/PasswordInput/index.tsx
  src/components/shared/RegularText/index.tsx
  src/components/shared/Section/index.tsx
  src/components/shared/Section/styles.ts
  src/components/shared/Separator/index.tsx
  src/components/shared/StyledInput/styles.ts
  src/components/shared/StyledInput/types.ts
  src/components/shared/Title/index.tsx
  src/components/shared/TitleInputWrapper/index.tsx
  src/locales/en/exampleTranslation.json
  src/pages/SignUpPage/index.tsx
  src/redux/exampleSlice.ts
  src/redux/store.ts
  src/theme.tsx
Labels: enhancement

#6 Feat/restore password screen
  src/assets/photos/restorePasswordPhoto.jpg
  src/components/RestorePasswordForm/index.tsx
  src/components/shared/BackgroundImage/index.tsx
  src/components/shared/InputWrapper/index.tsx
  src/components/shared/Logo/index.tsx
  src/components/shared/TitleInputWrapper/index.tsx
  src/locales/en/index.json
  src/pages/RestorePasswordPage/index.tsx
  src/routes/routes.tsx
Labels: enhancement

#7 feat: created otp input component, styled it, added the needed requir…
  .eslintrc.cjs
  src/components/shared/InputWrapper/index.tsx
  src/components/shared/OTPInput/OTP/OTPhook.ts
  src/components/shared/OTPInput/OTP/index.tsx
  src/components/shared/OTPInput/StyledOtpInput/index.ts
  src/components/shared/OTPInput/index.tsx
  src/components/shared/TitleInputWrapper/index.tsx
  src/locales/i18n.ts
  src/pages/VerifyEmailPage/VerifyEmailPageHooks.ts
  src/pages/VerifyEmailPage/index.tsx
  src/theme.tsx
Labels: enhancement

#8 Feat/reusable page container and markup
  src/assets/photos/newPasswordPhoto.jpeg
  src/assets/photos/signInPhoto.png
  src/assets/photos/signUpPhoto.jpeg
  src/assets/photos/verifyPhoto.jpeg
  src/components/RestorePasswordForm/index.tsx
  src/components/SignInForm/index.tsx
  src/components/SignInForm/styles.ts
  src/components/shared/BackgroundImage/index.tsx
  src/components/shared/Container/index.tsx
  src/components/shared/Logo/index.tsx
  src/components/shared/OTPInput/OTP.tsx
  src/components/shared/OTPInput/OTPInputHook.ts
  src/components/shared/OTPInput/index.tsx
  src/components/shared/Section/index.tsx
  src/components/shared/Section/sectionHook.ts
  src/components/shared/Section/styles.ts
  src/components/shared/StyledButton/index.tsx
  src/components/shared/StyledInput/index.tsx
  src/locales/en/index.json
  src/pages/NewPasswordPage/index.tsx
  src/pages/RestorePasswordPage/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/VerifyEmailPage/index.tsx
  src/routes/routes.tsx
Labels: enhancement

#9 feat/implemented validation for sign in form
  src/common/constants.ts
  src/components/SignInForm/index.tsx
  src/components/shared/PasswordInput/index.tsx
  src/components/shared/Section/sectionHook.ts
  src/components/shared/StyledButton/index.tsx
  src/locales/en/index.json
  src/pages/SignInPage/SignInForm.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignInPage/styles.ts
Labels: enhancement

#10 Feat/new password
  src/components/NewPasswordForm/index.tsx
  src/components/shared/PasswordInput/index.tsx
  src/locales/en/index.json
  src/pages/NewPasswordPage/index.tsx
Labels: enhancement

#12 Feat/connect backend and frontend for verify email
  .env.example
  .eslintrc.cjs
  package-lock.json
  package.json
  src/common/constants.ts
  src/components/shared/BackgroundImage/index.tsx
  src/components/shared/OTPInput/OTPInputHook.ts
  src/components/shared/OTPInput/StyledOtpInput/index.ts
  src/components/shared/PasswordInput/index.tsx
  src/components/shared/PolicyTermsLinks/index.tsx
  src/components/shared/PolicyTermsLinks/styles.ts
  src/components/shared/toasts/components/ToastProvider/index.tsx
  src/main.tsx
  src/pages/NewPasswordPage/NewPasswordForm/index.tsx
  src/pages/NewPasswordPage/index.tsx
  src/pages/PrivacyPolicyPage/index.tsx
  src/pages/RestorePasswordPage/RestorePasswordForm/index.tsx
  src/pages/RestorePasswordPage/index.tsx
  src/pages/SignInPage/SignInForm.tsx
  src/pages/SignInPage/SignInForm/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignInPage/styles.ts
  src/pages/SignUpPage/SignUpForm/index.tsx
  src/pages/SignUpPage/SignUpForm/styles.ts
  src/pages/SignUpPage/index.tsx
  src/pages/SignUpPage/styles.ts
  src/pages/TermsOfUsePage/index.tsx
  src/pages/VerifyEmailPage/VerifyEmailPageHooks.ts
  src/pages/VerifyEmailPage/hooks/useErrorHandling.ts
  src/pages/VerifyEmailPage/hooks/useOtp.ts
  src/pages/VerifyEmailPage/hooks/useTimer.ts
  src/pages/VerifyEmailPage/hooks/useVerification.ts
  src/pages/VerifyEmailPage/index.tsx
  src/pages/VerifyEmailPage/styles.ts
  src/redux/auth/authApi.ts
  src/redux/auth/authSlice.ts
  src/redux/auth/types/email.ts
  src/redux/auth/types/user.ts
  src/redux/hooks/index.ts
  src/redux/store.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/VerifyPrivateRoute.tsx
  src/routes/routes.tsx
Labels: enhancement

#11 Feat/signup
  .eslintrc.cjs
  src/common/constants.ts
  src/components/ExampleForm/index.tsx
  src/components/ExampleForm/styles.ts
  src/components/shared/Container/index.tsx
  src/components/shared/Logo/index.tsx
  src/components/shared/OTPInput/OTPInputHook.ts
  src/components/shared/Section/sectionHook.ts
  src/components/shared/SocialIconButton/index.tsx
  src/components/shared/StyledButton/index.tsx
  src/components/shared/toasts/components/ToastProvider/index.tsx
  src/main.tsx
  src/pages/NewPasswordPage/NewPasswordForm/index.tsx
  src/pages/NewPasswordPage/index.tsx
  src/pages/PrivacyPolicyPage/articles.ts
  src/pages/PrivacyPolicyPage/index.tsx
  src/pages/PrivacyPolicyPage/styles.ts
  src/pages/RestorePasswordPage/RestorePasswordForm/index.tsx
  src/pages/RestorePasswordPage/index.tsx
  src/pages/SignInPage/SignInForm/index.tsx
  src/pages/SignUpPage/SignUpForm/index.tsx
  src/pages/TermsOfUsePage/index.tsx
  src/pages/VerifyEmailPage/hooks/useErrorHandling.ts
  src/pages/VerifyEmailPage/hooks/useTimer.ts
  src/pages/VerifyEmailPage/hooks/useVerification.ts
  src/pages/VerifyEmailPage/index.tsx
  src/redux/auth/authSlice.ts
  src/redux/store.ts
  src/redux/user/service.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/theme.tsx
Labels: enhancement

#16 Feat/google
  .env.example
  package-lock.json
  package.json
  src/common/constants.ts
  src/components/GoogleAuthProvider/index.tsx
  src/components/GoogleLoginButton/index.tsx
  src/components/shared/StyledButton/index.tsx
  src/components/shared/TitleInputWrapper/index.tsx
  src/locales/en/index.json
  src/main.tsx
  src/pages/NewPasswordPage/NewPasswordForm/index.tsx
  src/pages/RestorePasswordPage/RestorePasswordForm/index.tsx
  src/pages/SignInAdminPage/SignInAdminForm/index.tsx
  src/pages/SignInPage/SignInForm/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/SignUpForm/index.tsx
  src/pages/SignUpPage/SignUpForm/schema.ts
  src/pages/SignUpPage/index.tsx
  src/pages/VerifyEmailPage/hooks/useVerification.ts
  src/pages/VerifyEmailPage/index.tsx
  src/redux/auth/authApi.ts
  src/redux/auth/authSlice.ts
  src/redux/auth/hooks/hooks.ts
  src/redux/auth/types/email.ts
  src/redux/auth/types/user.ts
  src/redux/store.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/VerifyPrivateRoute.tsx
  src/routes/routes.tsx
Labels: enhancement

#20 Feat/header footer
  src/App.css
  src/assets/icons/bag.svg
  src/assets/icons/bell.svg
  src/assets/icons/email.svg
  src/assets/icons/facebook.svg
  src/assets/icons/instagram.svg
  src/assets/icons/profile.svg
  src/common/constants.ts
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/FooterMenu/index.tsx
  src/components/FooterMenu/menuData.ts
  src/components/FooterMenu/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/components/HeaderLogo/index.tsx
  src/locales/en/index.json
  src/theme.tsx
Labels: markup

#21 Feat/admin
  src/assets/icons/admin/oval.svg
  src/assets/icons/admin/sort.svg
  src/assets/icons/close.svg
  src/assets/icons/delete-trash-red.svg
  src/assets/icons/search.svg
  src/common/constants.ts
  src/components/shared/SearchInput/index.tsx
  src/components/shared/SearchInput/styles.ts
  src/components/shared/StyledButton/styles.ts
  src/components/shared/StyledButton/types.ts
  src/locales/en/index.json
  src/pages/AdminUserProfileEditPage/index.tsx
  src/pages/AdminUserProfilePage/UserDetailsSection.tsx
  src/pages/AdminUserProfilePage/index.tsx
  src/pages/AdminUserProfilePage/styles.ts
  src/pages/TermsOfUsePage/styles.ts
  src/pages/admin/ActionButtons/index.tsx
  src/pages/admin/AdminLayout/index.tsx
  src/pages/admin/AdminLayout/styles.ts
  src/pages/admin/AdminSectionSubTitle/index.tsx
  src/pages/admin/AdminSectionTitle/index.tsx
  src/pages/admin/AdminSectionTitle/styles.ts
  src/pages/admin/AdminUserProfileEditPage/PhoneInput.tsx
  src/pages/admin/AdminUserProfileEditPage/ProfileInputWrapper.tsx
  src/pages/admin/AdminUserProfileEditPage/index.tsx
  src/pages/admin/AdminUserProfileEditPage/styles.ts
  src/pages/admin/AdminUserProfilePage/ProfileField.tsx
  src/pages/admin/AdminUserProfilePage/UserDetailsSection.tsx
  src/pages/admin/AdminUserProfilePage/index.tsx
  src/pages/admin/MainSection/index.tsx
  src/pages/admin/MainSection/styles.ts
  src/pages/admin/ModalPopup/index.tsx
  src/pages/admin/ModalPopup/styles.ts
  src/pages/admin/SignInAdminPage/SignInAdminForm/index.tsx
  src/pages/admin/SignInAdminPage/SignInAdminForm/styles.ts
  src/pages/admin/SignInAdminPage/index.tsx
  src/pages/admin/SignInAdminPage/styles.ts
  src/pages/admin/SortButton/index.tsx
  src/pages/admin/SortButton/styles.ts
  src/pages/admin/StyledBackdrop/index.tsx
  src/pages/admin/StyledPagination/index.tsx
  src/pages/admin/StyledPagination/styles.ts
  src/pages/admin/UsersPage/UsersTable/index.tsx
  src/pages/admin/UsersPage/UsersTable/styles.ts
  src/pages/admin/UsersPage/index.tsx
  src/pages/admin/UsersPage/styles.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: enhancement, markup

#22 Feat/onboarding
  src/App.css
  src/assets/icons/check-medium.svg
  src/assets/icons/user-image.svg
  src/common/constants.ts
  src/components/OnboardingCreditCardForm/index.tsx
  src/components/OnboardingCreditCardForm/styles.ts
  src/components/OnboardingHeaderItem/index.tsx
  src/components/OnboardingInfoForm/index.tsx
  src/components/OnboardingRoleForm/index.tsx
  src/components/OnboardingRoleForm/styles.ts
  src/components/OnboardingShippingForm/index.tsx
  src/components/OnboardingSizeForm/index.tsx
  src/components/shared/StyledButton/index.tsx
  src/components/shared/StyledButton/styles.ts
  src/components/shared/StyledButton/types.ts
  src/components/shared/StyledSelect/ExpandMoreIcon.tsx
  src/components/shared/StyledSelect/index.tsx
  src/components/shared/StyledSelect/styles.ts
  src/locales/en/index.json
  src/pages/HomePage/index.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/OnboardingPage/styles.ts
  src/pages/admin/SortButton/index.tsx
  src/pages/admin/UsersPage/index.tsx
  src/redux/user/types.ts
  src/redux/user/userSlice.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: enhancement, feature, markup

#23 Feat/admin
  src/common/constants.ts
  src/common/formatDateString.ts
  src/common/getInitials.ts
  src/components/HeaderAdmin/index.tsx
  src/components/HeaderAdmin/styles.ts
  src/components/SidebarAdmin/index.tsx
  src/components/shared/SearchInput/index.tsx
  src/components/shared/StyledButton/styles.ts
  src/locales/en/index.json
  src/pages/admin/ModalPopup/styles.ts
  src/pages/admin/SignInAdminPage/SignInAdminForm/index.tsx
  src/pages/admin/SortButton/index.tsx
  src/pages/admin/StyledPagination/index.tsx
  src/pages/admin/UsersPage/UsersTable/index.tsx
  src/pages/admin/UsersPage/UsersTable/styles.ts
  src/pages/admin/UsersPage/index.tsx
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/AdminPrivateRoute.tsx
  src/routes/routes.tsx
  src/theme.tsx
Labels: enhancement

#24 Feat/onboarding connection
  src/assets/photos/coming-soon.webp
  src/common/constants.ts
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/components/HeaderLogo/index.tsx
  src/components/Layout/index.tsx
  src/components/OnboardingCreditCardForm/index.tsx
  src/components/OnboardingInfoForm/index.tsx
  src/components/shared/Logo/index.tsx
  src/components/shared/StyledButton/index.tsx
  src/components/shared/StyledButton/types.ts
  src/locales/en/index.json
  src/pages/HomePage/index.tsx
  src/pages/OnboardingPage/CreditCardForm/index.tsx
  src/pages/OnboardingPage/CreditCardForm/schema.ts
  src/pages/OnboardingPage/CreditCardForm/styles.ts
  src/pages/OnboardingPage/HeaderItem/index.tsx
  src/pages/OnboardingPage/InfoForm/index.tsx
  src/pages/OnboardingPage/InfoForm/schema.ts
  src/pages/OnboardingPage/InfoForm/styles.ts
  src/pages/OnboardingPage/RoleForm/index.tsx
  src/pages/OnboardingPage/RoleForm/styles.ts
  src/pages/OnboardingPage/ShippingForm/index.tsx
  src/pages/OnboardingPage/ShippingForm/schema.ts
  src/pages/OnboardingPage/SizeForm/index.tsx
  src/pages/OnboardingPage/index.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/SignInPage/SignInForm/index.tsx
  src/pages/SizesGuidePage/index.tsx
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/OnboardingGuard.tsx
  src/routes/routes.tsx
Labels: enhancement, feature

#26 Feat/rtk requests for admin user profile
  src/common/constants.ts
  src/common/hooks/useErrorHandling.ts
  src/common/utils/extractPhoneNumberParts.ts
  src/common/utils/formatDateString.ts
  src/common/utils/formatUpdateDate.ts
  src/common/utils/getInitials.ts
  src/common/utils/hexToRgba.ts
  src/components/HeaderAdmin/index.tsx
  src/locales/en/index.json
  src/pages/VerifyEmailPage/hooks/useOtp.ts
  src/pages/VerifyEmailPage/hooks/useTimer.ts
  src/pages/VerifyEmailPage/hooks/useVerification.ts
  src/pages/VerifyEmailPage/index.tsx
  src/pages/admin/ActionButtons/index.tsx
  src/pages/admin/AdminLayout/index.tsx
  src/pages/admin/AdminUserProfileEditPage/PhoneInput.tsx
  src/pages/admin/AdminUserProfileEditPage/hooks/useUserProfileEdit.ts
  src/pages/admin/AdminUserProfileEditPage/index.tsx
  src/pages/admin/AdminUserProfileEditPage/styles.ts
  src/pages/admin/AdminUserProfileEditPage/types.ts
  src/pages/admin/AdminUserProfilePage/ProfileField.tsx
  src/pages/admin/AdminUserProfilePage/UserDetailsSection.tsx
  src/pages/admin/AdminUserProfilePage/hooks/useUserDetails.ts
  src/pages/admin/AdminUserProfilePage/index.tsx
  src/pages/admin/MainSection/styles.ts
  src/pages/admin/ModalPopup/index.tsx
  src/pages/admin/UsersPage/UsersTable/index.tsx
  src/pages/admin/UsersPage/UsersTable/styles.ts
  src/pages/admin/UsersPage/index.tsx
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/routes/AdminPrivateRoute.tsx
Labels: enhancement, feature

#25 Feat/profile
  src/assets/icons/edit-grey.svg
  src/assets/icons/edit-white.svg
  src/assets/photos/cooming-soon.webp
  src/common/constants.ts
  src/common/extractPhoneNumberParts.ts
  src/common/formatCardNumber.ts
  src/common/maskCardNumber.ts
  src/common/selectAdressOptions.ts
  src/common/selectSizeOptions.ts
  src/components/Header/index.tsx
  src/components/Layout/index.tsx
  src/components/shared/SectionTitle/index.tsx
  src/components/shared/SectionTitle/styles.ts
  src/components/shared/StyledInput/index.tsx
  src/components/shared/StyledSelect/index.tsx
  src/components/shared/StyledSelect/styles.ts
  src/locales/en/index.json
  src/pages/OnboardingPage/InfoForm/index.tsx
  src/pages/ProfileLayout/ProfileMenu/index.tsx
  src/pages/ProfileLayout/ProfileMenu/styles.ts
  src/pages/ProfileLayout/index.tsx
  src/pages/ProfileLayout/styles.ts
  src/pages/ProfilePage/AddressEditForm/index.tsx
  src/pages/ProfilePage/AddressEditForm/schema.ts
  src/pages/ProfilePage/AddressForm/index.tsx
  src/pages/ProfilePage/AddressForm/styles.ts
  src/pages/ProfilePage/PersonalInformationForm/index.tsx
  src/pages/ProfilePage/PersonalInformationForm/schema.ts
  src/pages/ProfilePage/PersonalInformationForm/styles.ts
  src/pages/ProfilePage/PhotoUploadForm/index.tsx
  src/pages/ProfilePage/PhotoUploadForm/styles.ts
  src/pages/ProfilePage/ProfileComingSoon/index.tsx
  src/pages/ProfilePage/ProfileMenu/index.tsx
  src/pages/ProfilePage/SizesFrom/index.tsx
  src/pages/ProfilePage/SizesFrom/styles.ts
  src/pages/ProfilePage/index.tsx
  src/pages/ProfilePage/styles.ts
  src/pages/ProfilePage/useErrorHandlingHook.ts
  src/redux/user/types.ts
  src/redux/user/userService.ts
  src/redux/user/userSlice.ts
  src/routes/routes.tsx
  src/theme.tsx
Labels: enhancement

#27 Feat/public profile page
  src/assets/icons/profile/star.svg
  src/common/constants.ts
  src/components/shared/CommentCard/index.tsx
  src/components/shared/CommentCard/styles.ts
  src/components/shared/CommentList/index.tsx
  src/locales/en/index.json
  src/pages/BuyerProfilePage/index.tsx
  src/pages/VendorProfilePage/ProfileInfo/index.tsx
  src/pages/VendorProfilePage/ProfileInfo/styles.ts
  src/pages/VendorProfilePage/index.tsx
  src/pages/VendorProfilePage/styles.ts
  src/routes/routes.tsx
Labels: enhancement

#28 Feat/product screen
  src/assets/icons/bag-check.svg
  src/assets/icons/chat-dots.svg
  src/assets/icons/heart.svg
  src/assets/photos/mockPhoto1.png
  src/assets/photos/mockPhoto2.png
  src/assets/photos/mockPhoto3.png
  src/assets/photos/mockPhoto4.png
  src/common/constants.ts
  src/locales/en/index.json
  src/pages/BuyerProfilePage/index.tsx
  src/pages/ProductPage/DescriptionSection.tsx
  src/pages/ProductPage/ImagesSection.tsx
  src/pages/ProductPage/ProductSection.tsx
  src/pages/ProductPage/RadioLabel.tsx
  src/pages/ProductPage/index.tsx
  src/pages/ProductPage/mockData.ts
  src/pages/ProductPage/styles.ts
  src/routes/routes.tsx
Labels: feature
